# Generated by Django 3.2.9 on 2021-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tag',
            new_name='tags',
        ),
    ]
